# Generated by Django 5.0.3 on 2024-08-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_de_pedido',
            field=models.CharField(default='pendiente'),
        ),
    ]
