# Generated by Django 5.0.3 on 2024-08-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_descripcion_pedido_estado_de_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sub_cantidad_pedida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
