# Generated by Django 5.0.3 on 2024-08-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_sub_cantidad_pedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_pedido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
