# Generated by Django 5.0.3 on 2024-08-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_id_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_pedido',
            new_name='numero_pedido',
        ),
    ]
