# Generated by Django 5.0.3 on 2024-08-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_id_pedido_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
